services:
  - type: web
    name: friend-finder-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: friend-finder-app
          property: port
    healthCheckPath: /api/me
